import assert from"node:assert/strict";import{test}from"node:test";import type{Actor,FormDefinition,Mutation,RecordData}from"../src/domain.js";import{validate}from"../src/domain.js";import{MemoryStore}from"../src/store.js";import{newOfflineRecord,retryDelayMs,SyncEngine}from"../src/sync.js";
const worker:Actor={id:"worker-1",role:"FIELD_WORKER"},coordinator:Actor={id:"coordinator-1",role:"COORDINATOR"};const form:FormDefinition={id:"assessment",version:1,title:"Assessment",active:true,fields:[{key:"location",label:"Location",type:"text",required:true},{key:"households",label:"Households",type:"number",required:true,min:1},{key:"priority",label:"Priority",type:"select",required:true,options:["LOW","HIGH"]}]};
async function setup(){const store=new MemoryStore();const sync=new SyncEngine(store,()=>new Date("2026-01-01T12:00:00Z"));await sync.saveForm(coordinator,form);return{store,sync}}
test("form validation rejects unknown missing and invalid values",()=>{assert.deepEqual(validate(form,{location:"Site A",households:2,priority:"HIGH"}),{});assert.deepEqual(validate(form,{location:"",households:0,priority:"OTHER",extra:true}),{extra:"unknown field",location:"required",households:"must be at least 1",priority:"must be an allowed option"})});
test("offline record queues with device and audit-safe metadata",()=>{const value=newOfflineRecord(form,{location:"Site A",households:4,priority:"LOW"},worker,"device-7",new Date("2026-01-01T10:00:00Z"));assert.equal(value.record.syncState,"PENDING");assert.equal(value.record.deviceId,"device-7");assert.equal(value.mutation.baseVersion,0)});
test("first synchronization persists and duplicate retry is idempotent",async()=>{const{store,sync}=await setup();const value=newOfflineRecord(form,{location:"Site A",households:4,priority:"LOW"},worker,"device");const first=await sync.apply(worker,value.mutation);assert.equal(first.status,"SYNCED");const retry=await sync.apply(worker,value.mutation);assert.equal(retry.status,"IDEMPOTENT");assert.equal((await store.read()).records.length,1)});
test("diverged base version creates conflict without overwriting remote",async()=>{const{store,sync}=await setup();const value=newOfflineRecord(form,{location:"Site A",households:4,priority:"LOW"},worker,"device");const saved=(await sync.apply(worker,value.mutation) as any).record as RecordData;const remoteMutation:Mutation={...value.mutation,mutationId:"remote-update",baseVersion:1,record:{...saved,values:{...saved.values,priority:"HIGH"}}};await sync.apply(worker,remoteMutation);const stale:Mutation={...value.mutation,mutationId:"stale-offline",baseVersion:1,record:{...saved,values:{...saved.values,households:8}}};const result=await sync.apply(worker,stale);assert.equal(result.status,"CONFLICT");assert.equal((await store.read()).records[0]?.values.priority,"HIGH")});
test("coordinator explicitly merges conflict and audit records strategy",async()=>{const{store,sync}=await setup();const value=newOfflineRecord(form,{location:"Site A",households:4,priority:"LOW"},worker,"device");const saved=(await sync.apply(worker,value.mutation)as any).record;await sync.apply(worker,{...value.mutation,mutationId:"remote",baseVersion:1,record:{...saved,values:{...saved.values,priority:"HIGH"}}});await sync.apply(worker,{...value.mutation,mutationId:"stale",baseVersion:1,record:{...saved,values:{...saved.values,households:9}}});const resolved=await sync.resolve(coordinator,saved.id,"MERGE",{location:"Site A",households:9,priority:"HIGH"});assert.equal(resolved.version,3);assert.equal((await store.read()).conflicts.length,0);assert.equal((await store.read()).audit.at(-1)?.metadata.strategy,"MERGE")});
test("retry backoff is exponential and capped",()=>{assert.deepEqual([1,2,3,20].map(x=>retryDelayMs(x)),[1000,2000,4000,300000])});
test("field workers cannot manage forms or resolve conflicts",async()=>{const sync=new SyncEngine(new MemoryStore());await assert.rejects(()=>sync.saveForm(worker,form),/permission denied/);await assert.rejects(()=>sync.resolve(worker,"x","REMOTE"),/permission denied/)});
