export const roles=["ADMIN","COORDINATOR","FIELD_WORKER","REVIEWER"] as const;export type Role=typeof roles[number];
export interface Actor{id:string;role:Role}
export type FieldType="text"|"number"|"boolean"|"select";
export interface FormField{key:string;label:string;type:FieldType;required:boolean;options?:string[];min?:number;max?:number}
export interface FormDefinition{id:string;version:number;title:string;fields:FormField[];active:boolean}
export type SyncState="PENDING"|"SYNCED"|"CONFLICT"|"FAILED";
export interface RecordData{id:string;formId:string;formVersion:number;values:Record<string,unknown>;version:number;createdAt:string;updatedAt:string;createdBy:string;updatedBy:string;deviceId:string;syncState:SyncState}
export interface Mutation{mutationId:string;recordId:string;baseVersion:number;record:RecordData;queuedAt:string;attempts:number;nextAttemptAt?:string}
export interface Conflict{recordId:string;mutationId:string;local:RecordData;remote:RecordData;detectedAt:string}
export interface AuditEvent{action:string;recordId:string;actorId:string;at:string;metadata:Record<string,unknown>}
export function can(actor:Actor,action:"form:manage"|"record:write"|"conflict:resolve"|"audit:read"){const matrix:Record<Role,string[]>={ADMIN:["form:manage","record:write","conflict:resolve","audit:read"],COORDINATOR:["form:manage","record:write","conflict:resolve","audit:read"],FIELD_WORKER:["record:write"],REVIEWER:["audit:read"]};return matrix[actor.role].includes(action)}
export function validate(form:FormDefinition,values:Record<string,unknown>){const errors:Record<string,string>={};const allowed=new Set(form.fields.map(x=>x.key));for(const key of Object.keys(values))if(!allowed.has(key))errors[key]="unknown field";for(const field of form.fields){const value=values[field.key];if(field.required&&(value===undefined||value===null||value==="")){errors[field.key]="required";continue}if(value===undefined||value===null)continue;if(field.type==="text"&&typeof value!=="string")errors[field.key]="must be text";if(field.type==="number"&&(typeof value!=="number"||!Number.isFinite(value)))errors[field.key]="must be a number";if(field.type==="boolean"&&typeof value!=="boolean")errors[field.key]="must be true or false";if(field.type==="select"&&!field.options?.includes(String(value)))errors[field.key]="must be an allowed option";if(typeof value==="number"&&field.min!==undefined&&value<field.min)errors[field.key]=`must be at least ${field.min}`;if(typeof value==="number"&&field.max!==undefined&&value>field.max)errors[field.key]=`must be at most ${field.max}`}return errors}
